pluginManagement {
	repositories {
		maven {
			name = 'Fabric'
			url = 'https://maven.fabricmc.net/'
		}
		mavenCentral()
		gradlePluginPortal()
	}
	plugins {
		id 'net.fabricmc.fabric-loom-remap' version "${loom_version}"
	}
}

rootProject.name = 'xaiac-server'
include 'common', 'fabric', 'paper'
